apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relatum-web.fullname" . }}
  labels:
    {{- include "relatum-web.labels" . | nindent 4 }}
data:
  RUST_LOG: {{ .Values.logLevel | quote }}
  RELATUM_WEB_LISTEN: {{ printf "0.0.0.0:%v" .Values.containerPort | quote }}
  RELATUM_WEB_API_URL: {{ .Values.config.apiUrl | quote }}
  RELATUM_WEB_PUBLIC_URL: {{ .Values.config.publicUrl | quote }}
  {{- with .Values.config.departments }}
  RELATUM_WEB_DEPARTMENTS: {{ join "," . | quote }}
  {{- end }}
